# --- CONFIGURACIÓN BÁSICA ---
spring.application.name=api-factus
server.port=${PORT:8080}

# --- IDENTIDAD DE VERSIÓN (ESTO ES LO QUE CAMBIA) ---
app.version=1.1.0
app.environment=GREEN

# --- ENDPOINTS DE TERCEROS ---
api.base_url=https://api-sandbox.factus.com.co
api.email=sandbox@factus.com.co
api.password=${API_PASSWORD}
api.client_id=${API_CLIENT_ID}
api.client_secret=${API_CLIENT_SECRET}

# --- MONITOREO Y SALUD (ACTUATOR) ---
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# Habilitar explícitamente el recolector de datos 'info'
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=${app.version}
info.app.env=${app.environment}

# --- LOGGING PROFESIONAL (BRANDING) ---
logging.file.name=logs/factus-api.log
# Este patrón hará que cada línea de log diga la versión, ideal para capturas de pantalla
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [VERSION ${app.version}] - %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.level.com.factus.api=DEBUG

# --- DOCUMENTACIÓN SWAGGER ---
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

