spring.application.name=api-factus
server.port=${PORT:8080}
api.base_url=https://api-sandbox.factus.com.co
api.email=sandbox@factus.com.co
api.password=sandbox2024%
api.client_id=9ed181b5-1a6f-434b-8d14-d69c0105f1a4
api.client_secret=SezQ5zrsP363CcuGoePu8a2jX4UkXb7iLilRWD3o
logging.file.name=logs/factus-api.log
# 2. Formato del log (Opcional, pero útil para seguridad: incluye fecha, nivel y clase)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# 3. Nivel de detalle para tu paquete específico
# Ponemos 'DEBUG' para que veas TODO lo que pasa en tu código mientras aprendes
logging.level.com.factus.api=DEBUG
# Habilitar Swagger UI
springdoc.swagger-ui.enabled=true
# Ruta personalizada (intenta acceder por aquí)
springdoc.swagger-ui.path=/swagger-ui.html

