spring.application.name=api-factus
server.port=${PORT:8080}
api.base_url=https://api-sandbox.factus.com.co
api.email=sandbox@factus.com.co
api.password=${API_PASSWORD}
api.client_id=${API_CLIENT_ID}
api.client_secret=${API_CLIENT_SECRET}
logging.file.name=logs/factus-api.log
# 2. Formato del log (Opcional, pero útil para seguridad: incluye fecha, nivel y clase)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# 3. Nivel de detalle para tu paquete específico
# Ponemos 'DEBUG' para que veas TODO lo que pasa en tu código mientras aprendes
logging.level.com.factus.api=DEBUG
# Habilitar Swagger UI
springdoc.swagger-ui.enabled=true
# Ruta personalizada (intenta acceder por aquí)
springdoc.swagger-ui.path=/swagger-ui.html

